### ISSUE TITLE
Gameplay Change: Animated Characters

### ISSUE THREAD

**Issue by bayers1** [bayers1/groupproject-team-lb#2]
Another more artistic-related change, this proposition revolves around the four playable dragons, who currently have static pngs for their designs, which, in an environment where they are supposed to be "flying", looks rather awkward and lifeless. Figuring out how to implement and loop animation would be an obvious yet crucial step in implementing this change.

**Comment by onzfonz** [comment]
I think this is the closest thing to have you work on, but I think as it is it may still be a lot for the span of what we have in the course.
What I would like you do is first figure out how to get it to switch between just two images, though the names of those images should either be in a folder that is read in or in a file would be the next step.
It does not have to switch between those images neatly or anything, (though you can use the timer to keep a counter and switch every 10 frames even when they aren't moving)
something like that is fine to start with and then you can gradually add more features.
The other parts just did not have as much programming, so this one has the heftiest amount, so go with this one.
